import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import "./globals.css";
import Topbar from "@/components/shared/Topbar";
import LeftSidebar from "@/components/shared/LeftSidebar";
import RightSideBar from "@/components/shared/RightSideBar";
import Bottombar from "@/components/shared/Bottombar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
    >
      <html lang='en'>
        <body className={`${inter.className} bg-dark-1 text-white`}>
          <Topbar/>
          <main>
            <LeftSidebar/>
            <section className="main_container">
              <div className="w-full max-x-4xl">
                {children}
              </div>
            </section>
            <RightSideBar/>
          </main>
          <Bottombar/>
        </body>
      </html>
    </ClerkProvider>
  );
}